### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by Naategh** [SaneBow/redirect-fuzzer#1]
When I'm trying run the script I'm getting this error:
```
Traceback (most recent call last):
  File "fuzz.py", line 418, in <module>
    with args.cookie_fp as fp:
AttributeError: __enter__
```

**Comment by SaneBow** [comment]
Thanks. It was fixed in https://github.com/SaneBow/redirect-fuzzer/commit/3a2f3e359637e345ee814d0cf9286ca248986d73#. Basically, this tool is only for checking OAuth `redirect_url` now and you must specify `--url` and `--cookie-file` for testing.

**Comment by Naategh** [comment]
Thanks.
